### PR TITLE
Added All 2022 Proposals

### PR DESCRIPTION
**Pull request by Tarun-Arora**

### CODE REVIEW

**Review by nishantwrp — APPROVED** [review]
lgtm, thanks!

**Comment by FoxSinOfGreed1729** [comment]
Could you please add my proposal to this list? Even I was selected for GSoC '22 :)

**Comment by nishantwrp** [comment]
Hi @DigvijayBhosale1729, sure. Can you make a pull request adding your proposal to the list?

**Comment by FoxSinOfGreed1729** [comment]
#3 
Added :)

**Pull request merged**
